name: Build and Deploy .NET Framework 4.8 App

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore DescopeSampleApp.sln

      - name: Build Solution
        run: msbuild DescopeSampleApp.sln /p:Configuration=Release

      - name: Copy build output to output folder
        run: |
          New-Item -ItemType Directory -Path output -Force
          Copy-Item -Path ".\DescopeSampleApp\bin\Release\*" -Destination .\output -Recurse -Force

      - name: Zip Build Output
        run: Compress-Archive -Path .\output\* -DestinationPath output.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: output.zip

  deploy:
    name: Deploy to Windows VM
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output

      - name: Copy to Windows VM via WinRM (PowerShell Remoting)
        uses: mlibre/powershell-ssh@v1
        with:
          host: ${{ secrets.WINDOWS_VM_IP }}
          username: ${{ secrets.WINDOWS_VM_USERNAME }}
          password: ${{ secrets.WINDOWS_VM_PASSWORD }}
          port: 5986
          inlineScript: |
            Expand-Archive -Path output.zip -DestinationPath "C:\inetpub\wwwroot" -Force
            Write-Output "✅ Deployment completed to C:\inetpub\wwwroot"
